config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  mount Shrine.presign_endpoint(:cache) => "/s3/params"

  if Rails.env.development? || Rails.env.test?
    mount Railsui::Engine, at: "/railsui"
  end

  get "pricing", to: "page#pricing"
  get "about", to: "page#about"

  get "invoice/:id", to: "orders#invoice", as: :invoice
  get "invoice_xml/:id", to: "orders#invoice_xml", as: :invoice_xml
  # create a namespace for admin
  namespace :admin do
    resources :products do
      collection do
        get :bulk_tag
        post :apply_bulk_tags
        get :search
        get :search_by_code
        get :search_by_name
        get :search_by_category
        get :search_by_subcategory
        get :search_by_brand
        get :search_by_tag
        get :search_by_barcode
        get :search_by_supplier
        get :search_by_price_range
        get :search_by_stock_range
        get :search_by_created_at
        get :search_by_updated_at
        get :search_by_status
        get :search_by_featured
        get :search_by_discount
        get :search_by_discount_range
        get :search_by_discount_start_date
        get :search_by_discount_end_date
        get :search_by_discount_status
        get :search_by_discount_type
        get :search_by_discount_value
        get :search_by_discount_value_range
        get :search_by_discount_percentage
        get :search_by_discount_percentage_range
        get :search_by_discount_amount
        get :search_by_discount_amount_range
        get :search_by_discount_min_quantity
        get :search_by_discount_max_quantity
        get :search_by_discount_min_amount
        get :search_by_discount_max_amount
        get :search_by_discount_min_percentage
        get :search_by_discount_max_percentage
        get :search_by_discount_min_value
        get :search_by_discount_max_value
        get :search_by_discount_min_created_at
        get :search_by_discount_max_created_at
        get :search_by_discount_min_updated_at
        get :search_by_discount_max_updated_at
        get :search_by_discount_min_start_date
        get :search_by_discount_max_start_date
        get :search_by_discount_min_end_date
        get :search_by_discount_max_end_date
        get :search_by_discount_min_status
        get :search_by_discount_max_status
        get :search_by_discount_min_type
        get :search_by_discount_max_type
        get :search_by_discount_min_value_range
        get :search_by_discount_max_value_range
        get :search_by_discount_min_percentage_range
        get :search_by_discount_max_percentage_range
        get :search_by_discount_min_amount_range
        get :search_by_discount_max_amount_range
        get :customer_prices
        get :default_prices
      end
      resources :media, module: :admin
      post "evaluate_group_discount", on: :collection
      get "search", on: :collection
      get "products_matching_tags", on: :collection
      get "customer_prices", on: :collection
      get "combo_products_show", on: :member
      member do
        get :stock
      end
    end

    resources :products_stock, only: [ :index ]

    post "face_recognition", to: "face_recognition#recognize"

    resources :product_categories, except: [ :show ] do
      resources :media, module: :admin
    end


    resources :requisitions do
      collection do
        get :new_automatic
      end
      member do
        patch :fulfill
      end
      resources :requisition_lines
    end

    resources :orders, only: [ :index, :new, :create, :update, :show, :edit, :update ] do
      member do
        post :retry_invoice
        get :universal_invoice_show
        get :edit_commissions
        get :edit_payments
        patch :update_payments
        post :void
        patch :toggle_wants_factura
      end
      collection do
        get "pos"
        get "orden_de_transporte_index", as: :orden_de_transporte_index
        get "new_orden_de_transporte", as: :new_orden_de_transporte
      end

      resources :external_invoices, only: [ :new, :create, :destroy ]
    end

    resources :voided_orders, only: [ :index, :show ]

    resources :settings, only: [ :index, :edit, :update ]

    resources :payments, only: [ :index, :show, :new, :create ]
    resources :payment_methods
    resources :price_lists
    resources :users do
      member do
        get "loyalty_info"
        patch "update_contact_info"
        get "check_roles"
        get "unpaid_orders"
      end
    end
    get "sellers", to: "users#sellers"

    resources :user_attendance_logs, only: [ :index, :new, :create, :edit, :update ] do
      collection do
        get "check_attendance_status"
        get "seller_checkout"
        get "seller_checkin_status"
        get "location_sellers"
        get "seller_attendance_report"
        get "location_attendance_report"
        post "compare_face"
      end
    end

    resources :customers
    post "pos_create_customer", to: "users#create_customer"
    get "search_dni", to: "customers#search_dni"
    get "search_ruc", to: "customers#search_ruc"

    resources :locations do
      member do
        get :commission_ranges
      end
      collection do
        get :sales_targets
      end
    end
    resources :commission_ranges
    resources :seller_biweekly_sales_targets do
      collection do
        get "seller_data"
      end
    end

    resources :warehouses
    patch "/set_current_warehouse", to: "warehouses#set_current_warehouse"
    get "inventory", to: "inventory/inventory#show"

    namespace :inventory do
      get "kardex", to: "kardex#show"
      get "fetch_kardex_movements", to: "kardex#fetch_kardex_movements"
      get "product_min_max_stocks", to: "product_min_max_stocks#index"
      post "product_min_max_stocks", to: "product_min_max_stocks#create"
      resources :periodic_inventories, only: [ :index, :new, :create, :show ] do
        collection do
          post :print_inventory_list
        end
      end
    end

    resources :stock_transfers do
      collection do
        get "index_stock_adjustments"
      end
      member do
        patch :set_to_in_transit
        get :initiate_receive
        post :execute_receive
        patch :adjustment_stock_transfer_admin_confirm
      end
    end
    post "generate_guia", to: "stock_transfers#generate_guia"
    resources :planned_stock_transfers do
      member do
        post :create_stock_transfer
      end
    end
    resources :in_transit_stocks
    resources :transportistas
    resources :combo_products
    resources :product_packs
    resources :discount_products
    resources :discounts do
      get "matching_products", on: :collection
    end
    resources :cashier_shifts do
      member do
        patch :close
        patch :modify_initial_balance
      end
    end

    resources :cashier_transactions, only: [ :new, :create ]
    resources :commissions, only: [ :index, :show ]
    resources :loyalty_tiers
    resources :invoicers do
      get "invoice_series", on: :member
    end
    resources :invoice_series
    resources :invoice_series_mappings

    resources :tags, only: [ :index, :new, :create, :edit, :update, :destroy ]

    resources :account_receivables, only: [ :index, :show ] do
      get "users_index", on: :collection
      get "payments_calendar", on: :collection
      post "create_initial_balance", on: :collection
    end

    resources :account_receivable_payments do
      collection do
        get :success
        get :error
      end
    end

    resources :purchase_orders do
      member do
        post :create_purchase
      end
      collection do
        get :get_product_details
      end
    end

    resources :purchases do
      collection do
        get :get_purchase_order_details
        get :get_product_details
        get :check_invoice_custom_id
      end
    end

    resources :purchase_invoices

    resources :vendors

    resources :purchase_payments, only: [ :index, :show, :new, :create ] do
      collection do
        get :fetch_purchases
      end
    end

    resources :account_payables, only: [ :index, :show ] do
      collection do
        get :vendors_index
        get :payments_calendar
        post :create_initial_balance
      end
    end

    resources :account_payable_payments do
      collection do
        get :success
        get :error
      end
    end

    resources :orders_per_product, only: [ :index ] do
      collection do
        get :reset_filters
      end
    end

    get "sales_dashboard", to: "dashboards#sales_dashboard"
    get "cashiers_dashboard", to: "dashboards#cashiers_dashboard"
    get "sales_ranking", to: "dashboards#sales_ranking"
    post "dashboards/set_location", to: "dashboards#set_location"

    resources :dashboards, only: [] do
      collection do
        get :payments_calendar
      end
    end

    get "reports/form", to: "reports#reports_form"
    post "reports/generate", to: "reports#generate"
    get "reports/cash_flow", to: "reports#cash_flow"
    get "reports/inventory_out", to: "reports#inventory_out"
    get "reports/consolidated", to: "reports#consolidated"

    resources :consolidated_sales, only: [ :index ]
    get "reports/consolidated_sales", to: "consolidated_sales#index"

    resources :sales_per_seller, only: [ :index ] do
      collection do
        get :consolidated
      end
    end
    get "reports/sales_per_seller", to: "sales_per_seller#index"
    get "reports/sales_per_seller/consolidated", to: "sales_per_seller#consolidated"

    resources :flat_commission_products_report, only: [ :index ]
    get "reports/flat_commission_products_report", to: "flat_commission_products_report#index"

    resources :grouped_sales, only: [ :index ]
    get "reports/grouped_sales", to: "grouped_sales#index"

    resources :stock_transfers_with_differences, only: [ :index ] do
      member do
        put :accept_origin_quantity
        put :accept_destination_quantity
      end

app/models/commission_range.rb
# app/models/commission_range.rb
class CommissionRange < ApplicationRecord
  belongs_to :user
  belongs_to :location

  # Validations
  validates :min_sales, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :max_sales, numericality: { greater_than: :min_sales }, allow_nil: true
  validates :commission_percentage, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :year_month_period, presence: true

  # Scope for easier querying of commission ranges within specific sales amounts
  scope :for_sales, ->(sales) { where("min_sales <= ? AND (max_sales IS NULL OR max_sales >= ?)", sales, sales) }
  scope :for_period, ->(year_month_period) { where(year_month_period: year_month_period) }

  # Method to find applicable commission for a given sales amount
  def self.find_commission_for_sales(sales, location, date)
    for_sales(sales).where(location_id: location.id, year_month_period: generate_year_month_period(date)).order(:min_sales).last
  end

  def self.generate_year_month_period(date)
    year = date.year
    month = date.month
    period = date.day <= 15 ? "I" : "II"
    "#{year}_#{month.to_s.rjust(2, '0')}_#{period}"
  end

  def self.current_year_month_period
    generate_year_month_period(Date.current)
  end
end

app/controllers/admin/commission_ranges_controller.rb
class Admin::CommissionRangesController < Admin::AdminController
  before_action :set_commission_range, only: [ :edit, :update, :destroy ]

  def index
    authorize! :read, CommissionRange

    @commission_ranges = if @current_location
      CommissionRange.where(location: @current_location)
                    .includes(:location)
                    .order("locations.name, min_sales")
    else
      CommissionRange.includes(:location)
                    .order("locations.name, min_sales")
    end

    @datatable_options = "resource_name:'CommissionRange';create_button:true;sort_0_asc;sort_1_asc;"

    respond_to do |format|
      format.html # index.html.erb
      format.turbo_stream { render turbo_stream: turbo_stream.replace("commission-ranges-table", partial: "admin/commission_ranges/table", locals: { commission_ranges: @commission_ranges }) }
    end
  end

  def new
    authorize! :create, CommissionRange
    @commission_range = CommissionRange.new
    period = Date.today.day <= 15 ? "I" : "II"
    @commission_range.year_month_period = "#{Date.today.strftime('%Y_%m')}_#{period}"
    @location = params[:location_id].present? ? Location.find(params[:location_id]) : (@current_location || Location.first)
  end

  def create
    authorize! :create, CommissionRange
    @commission_range = CommissionRange.create(commission_range_params)
    redirect_to admin_commission_ranges_path
  end

  def edit
    authorize! :update, @commission_range
    set_commission_range
    @location = @commission_range.location
  end

  def update
    authorize! :update, @commission_range
    set_commission_range
    @commission_range.update(commission_range_params)
    redirect_to admin_commission_ranges_path
  end

  def destroy
    authorize! :destroy, @commission_range
    set_commission_range
    @commission_range.destroy
    redirect_to admin_commission_ranges_path
  end

  private

  def set_commission_range
    @commission_range = CommissionRange.find(params[:id])
  end

  def commission_range_params
    params.require(:commission_range).permit(:start_amount, :end_amount, :commission_percentage, :year_month_period, :location_id)
  end
end

app/views/admin/commission_ranges/_commission_range_fields.html.erb
<!-- app/views/admin/locations/_commission_range_fields.html.erb -->
<div class="flex items-center mb-4 space-x-4 nested-fields" data-new-record="<%= form.object.new_record? %>">
  
  <!-- Year Month Period -->
  <div class="flex-1">
    <%= form.input :year_month_period, label: 'Periodo (Año_Mes_Semestre)', input_html: { class: 'form-input block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-primary-500 focus:border-primary-500 sm:text-sm', value: @commission_range.year_month_period } %>
  </div>
  
  <!-- Min Sales -->
  <div class="flex-1">
    <%= form.input :min_sales, label: 'Ventas Desde', input_html: { step: 0.01, class: 'form-input block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-primary-500 focus:border-primary-500 sm:text-sm' } %>
  </div>

  <!-- Max Sales -->
  <div class="flex-1">
    <%= form.input :max_sales, label: 'Ventas Hasta', input_html: { step: 0.01, class: 'form-input block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-primary-500 focus:border-primary-500 sm:text-sm' } %>
  </div>

  <!-- Commission Percentage -->
  <div class="flex-1">
    <%= form.input :commission_percentage, label: 'Porcentaje de Comisión', input_html: { step: 0.01, class: 'form-input block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-primary-500 focus:border-primary-500 sm:text-sm' } %>
  </div>

  <!-- Remove Button -->
  <div>
    <%= link_to '✖', '#', class: 'text-red-600 hover:text-red-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500', data: { action: 'click->commission-range-form#removeAssociation' } %>
  </div>

  <%= form.hidden_field :_destroy %>
  <%= form.hidden_field :user_id, value: current_user.id %>
</div>

app/views/admin/commission_ranges/_form.html.erb
<%= simple_form_for location, url: admin_location_path(location), method: :patch, html: { class: 'space-y-6', data: { controller: 'commission-range-form', commissionRangeFormLocationValue: location.id, turbo: false } } do |f| %>


  <!-- Location Details -->
  <div class="mb-5">
    <%= select_tag 'location_id', options_for_select(Location.active.all.collect { |l| [l.name, l.id] }, location.id), prompt: "Selecciona la Tienda", class: "form-input block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-primary-500 focus:border-primary-500 sm:text-sm", data: { action: 'change->commission-range-form#locationChanged' } %>
  </div>

  <!-- Hidden Input to Track the Selected Location -->
  <%= hidden_field_tag 'selected_location_id', location.id, data: { commission_range_form_target: 'selectedLocation' } %>


  <!-- Commission Ranges -->
  <div data-controller="commission-range-form">
    <!-- Template for New Commission Ranges -->
    <template data-commission-range-form-target="commissionRangeTemplate">
      <%= f.simple_fields_for :commission_ranges, CommissionRange.new, child_index: 'NEW_RECORD' do |commission_form| %>
        <%= render 'commission_range_fields', form: commission_form %>
      <% end %>
    </template>

    <div id="commission-ranges">
      <%= f.simple_fields_for :commission_ranges do |commission_form| %>
        <%= render 'commission_range_fields', form: commission_form %>
      <% end %>
    </div>

    <!-- Add New Commission Range Button -->
    <div class="mt-4" data-commission-range-form-target="links">
      <%= link_to 'Agregar Rango', '#', class: 'btn btn-secondary inline-block px-4 py-2 text-sm font-medium text-white bg-blue-600 border border-transparent rounded-md shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500', data: { action: 'click->commission-range-form#addAssociation' } %>
    </div>
  </div>

  <!-- Submit Button -->
  <div class="flex items-center py-6 mt-10 space-x-4 border-t border-gray-200 dark:border-slate-600">
    <%= f.submit 'Grabar', class: 'btn btn-primary inline-block px-4 py-2 text-sm font-medium text-white bg-green-600 border border-transparent rounded-md shadow-sm hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500' %>
    <%= link_to 'Cancelar', admin_commission_ranges_path(location_id: location.id), class: 'inline-block px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' %>
  </div>
<% end %>

app/views/admin/commission_ranges/_table.html.erb
<div id="commission-ranges-table" data-controller="datatable" data-datatable-options-value="<%= @datatable_options %>">
  <div class="container p-2 mx-auto mt-6 overflow-x-auto bg-white border rounded-lg shadow border-slate-300/80 shadow-slate-100 dark:shadow-slate-950 dark:bg-slate-800 dark:border-slate-600/80">
    <table id="datatable-element" class="min-w-full bg-white dark:bg-slate-800">
      <thead>
        <tr>
          <th class="px-4 py-2 text-left">Tienda</th>
          <th class="px-4 py-2 text-left">Periodo</th>
          <th class="px-4 py-2 text-left">Ventas Mínimas</th>
          <th class="px-4 py-2 text-left">Ventas Máximas</th>
          <th class="px-4 py-2 text-left">Porcentaje de Comisión</th>
          <th class="px-4 py-2 text-left">Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% @commission_ranges.each do |commission_range| %>
          <tr>
            <td class="px-4 py-2"><%= commission_range.location.name %></td>
            <td class="px-4 py-2"><%= commission_range.year_month_period %></td>
            <td class="px-4 py-2"><%= format_currency(commission_range.min_sales) %></td>
            <td class="px-4 py-2"><%= format_currency(commission_range.max_sales) || 'Infinito' %></td>
            <td class="px-4 py-2"><%= commission_range.commission_percentage %> %</td>
            <td class="px-4 py-2">
              <%= link_to 'Editar', edit_admin_commission_range_path(commission_range), class: 'btn btn-secondary' %>
              <%= link_to 'Eliminar', admin_commission_range_path(commission_range), method: :delete, data: { turbo_confirm: '¿Estás seguro?' }, class: 'btn btn-danger', data: { turbo_method: :delete } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/commission_ranges/edit.html.erb
<!-- app/views/commission_ranges/edit.html.erb -->
<%= render "shared/admin/nav", { header_title: "Editar Rango de Comisión" } do %>
<% end %>

<div class="container p-6 mx-auto mt-6 bg-white border rounded-lg shadow border-slate-300/80 shadow-slate-100 dark:shadow-slate-950 dark:bg-slate-800 dark:border-slate-600/80">
  <%= render 'form', commission_range: @commission_range, location: @location %>
</div>

app/views/admin/commission_ranges/index.html.erb
<%= render "shared/admin/nav", { header_title: "Rangos de Comisión Local#{@current_location ? " - #{@current_location.name}" : ''}" } do %>
  <%= render "shared/admin/location_dropdown" %>
<% end %>

<div class="px-4 mb-16">
  <%= render 'table', commission_ranges: @commission_ranges %>
</div>

app/views/admin/commission_ranges/new.html.erb
<!-- app/views/commission_ranges/new.html.erb -->
<%= render "shared/admin/nav", { header_title: "Crear Nuevo Rango de Comisión" } do %>
<% end %>

<div class="container p-6 mx-auto mt-6 bg-white border rounded-lg shadow border-slate-300/80 shadow-slate-100 dark:shadow-slate-950 dark:bg-slate-800 dark:border-slate-600/80">
  <%= render 'form', commission_range: @commission_range, location: @location %>
</div>