config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  mount Shrine.presign_endpoint(:cache) => "/s3/params"

  if Rails.env.development? || Rails.env.test?
    mount Railsui::Engine, at: "/railsui"
  end

  get "pricing", to: "page#pricing"
  get "about", to: "page#about"

  get "invoice/:id", to: "orders#invoice", as: :invoice
  get "invoice_xml/:id", to: "orders#invoice_xml", as: :invoice_xml
  # create a namespace for admin
  namespace :admin do
    resources :products do
      collection do
        get :bulk_tag
        post :apply_bulk_tags
        get :search
        get :search_by_code
        get :search_by_name
        get :search_by_category
        get :search_by_subcategory
        get :search_by_brand
        get :search_by_tag
        get :search_by_barcode
        get :search_by_supplier
        get :search_by_price_range
        get :search_by_stock_range
        get :search_by_created_at
        get :search_by_updated_at
        get :search_by_status
        get :search_by_featured
        get :search_by_discount
        get :search_by_discount_range
        get :search_by_discount_start_date
        get :search_by_discount_end_date
        get :search_by_discount_status
        get :search_by_discount_type
        get :search_by_discount_value
        get :search_by_discount_value_range
        get :search_by_discount_percentage
        get :search_by_discount_percentage_range
        get :search_by_discount_amount
        get :search_by_discount_amount_range
        get :search_by_discount_min_quantity
        get :search_by_discount_max_quantity
        get :search_by_discount_min_amount
        get :search_by_discount_max_amount
        get :search_by_discount_min_percentage
        get :search_by_discount_max_percentage
        get :search_by_discount_min_value
        get :search_by_discount_max_value
        get :search_by_discount_min_created_at
        get :search_by_discount_max_created_at
        get :search_by_discount_min_updated_at
        get :search_by_discount_max_updated_at
        get :search_by_discount_min_start_date
        get :search_by_discount_max_start_date
        get :search_by_discount_min_end_date
        get :search_by_discount_max_end_date
        get :search_by_discount_min_status
        get :search_by_discount_max_status
        get :search_by_discount_min_type
        get :search_by_discount_max_type
        get :search_by_discount_min_value_range
        get :search_by_discount_max_value_range
        get :search_by_discount_min_percentage_range
        get :search_by_discount_max_percentage_range
        get :search_by_discount_min_amount_range
        get :search_by_discount_max_amount_range
        get :customer_prices
        get :default_prices
      end
      resources :media, module: :admin
      post "evaluate_group_discount", on: :collection
      get "search", on: :collection
      get "products_matching_tags", on: :collection
      get "customer_prices", on: :collection
      get "combo_products_show", on: :member
      member do
        get :stock
      end
    end

    resources :products_stock, only: [ :index ]

    post "face_recognition", to: "face_recognition#recognize"

    resources :product_categories, except: [ :show ] do
      resources :media, module: :admin
    end


    resources :requisitions do
      collection do
        get :new_automatic
      end
      member do
        patch :fulfill
      end
      resources :requisition_lines
    end

    resources :orders, only: [ :index, :new, :create, :update, :show, :edit, :update ] do
      member do
        post :retry_invoice
        get :universal_invoice_show
        get :edit_commissions
        get :edit_payments
        patch :update_payments
        post :void
        patch :toggle_wants_factura
      end
      collection do
        get "pos"
        get "orden_de_transporte_index", as: :orden_de_transporte_index
        get "new_orden_de_transporte", as: :new_orden_de_transporte
      end

      resources :external_invoices, only: [ :new, :create, :destroy ]
    end

    resources :voided_orders, only: [ :index, :show ]

    resources :settings, only: [ :index, :edit, :update ]

    resources :payments, only: [ :index, :show, :new, :create ]
    resources :payment_methods
    resources :price_lists
    resources :users do
      member do
        get "loyalty_info"
        patch "update_contact_info"
        get "check_roles"
        get "unpaid_orders"
      end
    end
    get "sellers", to: "users#sellers"

    resources :user_attendance_logs, only: [ :index, :new, :create, :edit, :update ] do
      collection do
        get "check_attendance_status"
        get "seller_checkout"
        get "seller_checkin_status"
        get "location_sellers"
        get "seller_attendance_report"
        get "location_attendance_report"
        post "compare_face"
      end
    end

    resources :customers
    post "pos_create_customer", to: "users#create_customer"
    get "search_dni", to: "customers#search_dni"
    get "search_ruc", to: "customers#search_ruc"

    resources :locations do
      member do
        get :commission_ranges
      end
      collection do
        get :sales_targets
      end
    end
    resources :commission_ranges
    resources :seller_biweekly_sales_targets do
      collection do
        get "seller_data"
      end
    end

    resources :warehouses
    patch "/set_current_warehouse", to: "warehouses#set_current_warehouse"
    get "inventory", to: "inventory/inventory#show"

    namespace :inventory do
      get "kardex", to: "kardex#show"
      get "fetch_kardex_movements", to: "kardex#fetch_kardex_movements"
      get "product_min_max_stocks", to: "product_min_max_stocks#index"
      post "product_min_max_stocks", to: "product_min_max_stocks#create"
      resources :periodic_inventories, only: [ :index, :new, :create, :show ] do
        collection do
          post :print_inventory_list
        end
      end
    end

    resources :stock_transfers do
      collection do
        get "index_stock_adjustments"
      end
      member do
        patch :set_to_in_transit
        get :initiate_receive
        post :execute_receive
        patch :adjustment_stock_transfer_admin_confirm
      end
    end
    post "generate_guia", to: "stock_transfers#generate_guia"
    resources :planned_stock_transfers do
      member do
        post :create_stock_transfer
      end
    end
    resources :in_transit_stocks
    resources :transportistas
    resources :combo_products
    resources :product_packs
    resources :discount_products
    resources :discounts do
      get "matching_products", on: :collection
    end
    resources :cashier_shifts do
      member do
        patch :close
        patch :modify_initial_balance
      end
    end

    resources :cashier_transactions, only: [ :new, :create ]
    resources :commissions, only: [ :index, :show ]
    resources :loyalty_tiers
    resources :invoicers do
      get "invoice_series", on: :member
    end
    resources :invoice_series
    resources :invoice_series_mappings

    resources :tags, only: [ :index, :new, :create, :edit, :update, :destroy ]

    resources :account_receivables, only: [ :index, :show ] do
      get "users_index", on: :collection
      get "payments_calendar", on: :collection
      post "create_initial_balance", on: :collection
    end

    resources :account_receivable_payments do
      collection do
        get :success
        get :error
      end
    end

    resources :purchase_orders do
      member do
        post :create_purchase
      end
      collection do
        get :get_product_details
      end
    end

    resources :purchases do
      collection do
        get :get_purchase_order_details
        get :get_product_details
        get :check_invoice_custom_id
      end
    end

    resources :purchase_invoices

    resources :vendors

    resources :purchase_payments, only: [ :index, :show, :new, :create ] do
      collection do
        get :fetch_purchases
      end
    end

    resources :account_payables, only: [ :index, :show ] do
      collection do
        get :vendors_index
        get :payments_calendar
        post :create_initial_balance
      end
    end

    resources :account_payable_payments do
      collection do
        get :success
        get :error
      end
    end

    resources :orders_per_product, only: [ :index ] do
      collection do
        get :reset_filters
      end
    end

    get "sales_dashboard", to: "dashboards#sales_dashboard"
    get "cashiers_dashboard", to: "dashboards#cashiers_dashboard"
    get "sales_ranking", to: "dashboards#sales_ranking"
    post "dashboards/set_location", to: "dashboards#set_location"

    resources :dashboards, only: [] do
      collection do
        get :payments_calendar
      end
    end

    get "reports/form", to: "reports#reports_form"
    post "reports/generate", to: "reports#generate"
    get "reports/cash_flow", to: "reports#cash_flow"
    get "reports/inventory_out", to: "reports#inventory_out"
    get "reports/consolidated", to: "reports#consolidated"

    resources :consolidated_sales, only: [ :index ]
    get "reports/consolidated_sales", to: "consolidated_sales#index"

    resources :sales_per_seller, only: [ :index ] do
      collection do
        get :consolidated
      end
    end
    get "reports/sales_per_seller", to: "sales_per_seller#index"
    get "reports/sales_per_seller/consolidated", to: "sales_per_seller#consolidated"

    resources :flat_commission_products_report, only: [ :index ]
    get "reports/flat_commission_products_report", to: "flat_commission_products_report#index"

    resources :grouped_sales, only: [ :index ]
    get "reports/grouped_sales", to: "grouped_sales#index"

    resources :stock_transfers_with_differences, only: [ :index ] do
      member do
        put :accept_origin_quantity
        put :accept_destination_quantity
      end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def invoice
    @order = Order.find(params[:id])
    @invoice_result = @order.universal_invoice_show

    case @invoice_result[:status]
    when :ready
      redirect_to @invoice_result[:url], allow_other_host: true
    when :pending
      render json: { message: @invoice_result[:message] }, status: :ok
    else
      render plain: "Ocurrió un error al generar el comprobante. Por favor, inténtelo de nuevo más tarde.", status: :internal_server_error
    end
  end

  def invoice_xml
    @order = Order.find(params[:id])
    xml_url = @order.universal_xml_link

    # Validate the URL is from your trusted domain(s)
    if trusted_invoice_url?(xml_url)
      # brakeman:ignore:redirect
      redirect_to xml_url, allow_other_host: true
    else
      render plain: "Invalid invoice URL", status: :bad_request
    end
  end

  private

  def trusted_invoice_url?(url)
    return false if url.blank?

    # Add your trusted domains here
    trusted_domains = [
      "www.nubefact.com",
      "nubefact.com"
    ]

    begin
      uri = URI.parse(url)
      trusted_domains.any? { |domain| uri.host == domain }
    rescue URI::InvalidURIError
      false
    end
  end
end

app/views/admin/orders/_edit_action.html.erb
<%= link_to edit_admin_order_path(order), class: "px-4 py-[.4rem] group flex items-center justify-start space-x-3" do %>
  <%= icon "pencil", classes: "stroke-current w-5 h-5 text-slate-500 group-hover:text-primary-600 dark:group-hover:text-primary-400" %>
<% end %>

app/views/admin/orders/_view_action.html.erb
<%= link_to admin_order_path(order), class: "px-4 py-[.4rem] group flex items-center justify-start space-x-3" do %>
  <%= icon "eye", classes: "stroke-current w-5 h-5 text-slate-500 group-hover:text-primary-600 dark:group-hover:text-primary-400" %>
<% end %>

app/views/admin/orders/_void_action.html.erb
<%= link_to void_admin_order_path(order), data: { turbo_confirm: "¿Estás seguro de que deseas anular esta orden?", turbo_method: :post }, class: "px-4 py-[.4rem] group flex items-center justify-start space-x-3" do %>
  <%= icon "x-mark", classes: "stroke-current w-5 h-5 text-slate-500 group-hover:text-primary-600 dark:group-hover:text-primary-400" %>
<% end %>

app/views/admin/orders/edit_commissions.html.erb
<%= render "shared/admin/nav", { header_title: "Editar Comisiones - Venta ##{@order.custom_id}" } do %>
  <%= link_to "Volver a Venta", admin_order_path(@order), class: "btn btn-secondary" %>
<% end %>

<div class="container px-4 py-8 mx-auto">
  <%= render 'commission_form' %>
</div>

app/views/admin/orders/edit_payments.html.erb
<%= render "shared/admin/nav", { header_title: "Editar Pagos - Venta ##{@order.custom_id}" } do %>
  <%= link_to "Volver a Venta", admin_order_path(@order), class: "btn btn-secondary" %>
<% end %>

<div class="container px-4 py-8 mx-auto">
  <%= simple_form_for [:admin, @order], url: update_payments_admin_order_path(@order), html: { data: { controller: "payment-editor", payment_editor_total_value: @order.total_price_cents } } do |f| %>
    <%= render "shared/error_messages", resource: @order %>
    
    <!-- Order Total and Summary -->
    <div class="max-w-5xl p-6 mx-auto mb-8 bg-white border border-gray-200 rounded-lg shadow-md">
      <div class="p-4 mb-6 rounded-lg bg-gray-50">
        <div class="flex items-center justify-between">
          <h3 class="text-lg font-medium">Editar Pagos</h3>
          <div class="text-right">
            <p class="text-sm text-gray-600">Monto Total de Venta</p>
            <p class="text-xl font-semibold" data-payment-editor-target="orderTotal">
              <%= format_currency(@order.total_price) %>
            </p>
          </div>
        </div>
        <div class="mt-2">
          <div class="flex justify-end space-x-4">
            <p class="text-sm text-gray-600">
              Total Asignado: 
              <span data-payment-editor-target="assignedTotal" class="font-semibold">S/ 0.00</span>
            </p>
            <p class="text-sm text-gray-600">
              Disponible: 
              <span data-payment-editor-target="remainingTotal" class="font-semibold"><%= format_currency(@order.total_price) %></span>
            </p>
          </div>
        </div>
      </div>

      <div class="space-y-4" data-payment-editor-target="lines">
        <% if @order.payments.empty? %>
          <%= f.simple_fields_for :payments, Payment.new do |payment_form| %>
            <%= render 'payment_fields', f: payment_form %>
          <% end %>
        <% else %>
          <%= f.simple_fields_for :payments do |payment_form| %>
            <%= render 'payment_fields', f: payment_form %>
          <% end %>
        <% end %>
      </div>

      <div class="flex items-center justify-between py-6 mt-6 border-t">
        <button type="button" class="btn btn-outline" data-action="click->payment-editor#addPayment">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
          </svg>
          Agregar Método de Pago
        </button>

        <div class="flex items-center space-x-4">
          <%= f.submit "Guardar Cambios", 
              class: "btn btn-primary", 
              data: { 
                payment_editor_target: "submitButton",
                disable_with: "Guardando..." 
              } %>
          <%= link_to "Cancelar", admin_order_path(@order), class: "btn btn-secondary" %>
        </div>
      </div>

      <%# Template for new payments %>
      <template id="payment-template">
        <%= f.simple_fields_for :payments, Payment.new, child_index: "NEW_RECORD" do |payment_form| %>
          <%= render 'payment_fields', f: payment_form %>
        <% end %>
      </template>
    </div>
  <% end %>
</div>

app/views/admin/orders/index.html.erb
<%= render "shared/admin/nav", { header_title: "Ventas#{@current_location ? " - #{@current_location.name}" : ''}" } do %>
  <%= render "shared/admin/location_dropdown" %>
  <%= render "shared/admin/create_dropdown" %>
<% end %>

<div class="px-4 mb-16" data-controller="datatable" data-datatable-options-value="<%= @datatable_options %>">
  <div class="container p-2 mx-auto mt-6 bg-white rounded-lg border shadow border-slate-300/80 shadow-slate-100 dark:shadow-slate-950 dark:bg-slate-800 dark:border-slate-600/80">
    <table id="datatable-element" class="min-w-full bg-white dark:bg-slate-800">
      <thead>
        <tr>
          <th class="px-4 py-2 text-left">ID</th>
          <% if current_user.any_admin_or_supervisor? %>
            <th class="px-4 py-2 text-left">Tienda</th>
          <% end %>
          <th class="px-4 py-2 text-left">Número</th>
          <th class="px-4 py-2 text-left">Fecha</th>
          <th class="px-4 py-2 text-left">Comprador</th>
          <th class="px-4 py-2 text-left">Total</th>
          <th class="px-4 py-2 text-left">Total Original</th>
          <th class="px-4 py-2 text-left">Descuento</th>
          <th class="px-4 py-2 text-left">Comprobante</th>
          <th class="px-4 py-2 text-left">XML</th>
          <th class="px-4 py-2 text-left">Estado Pago</th>
          <th class="px-4 py-2 text-left">Estado</th>
          <% if $global_settings[:feature_flag_sales_attributed_to_seller] %>
            <th class="px-4 py-2 text-left">Comisión</th>
          <% end %>
          <th class="px-4 py-2 text-left">Ver</th>
          <% if current_user.any_admin_or_supervisor? %>
            <th class="px-4 py-2 text-left">Editar</th>
          <% end %>
          <th class="px-4 py-2 text-left">Anular</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td class="px-4 py-2"><%= order.id %></td>
            <% if current_user.any_admin_or_supervisor? %>
              <td class="px-4 py-2"><%= order.location.name %></td>
            <% end %>
            <td class="px-4 py-2"><%= order.custom_id %></td>
            <td class="px-4 py-2"><%= friendly_date(current_user, order.order_date) %></td>
            <td class="px-4 py-2"><%= order&.customer&.name %></td>
            <td class="px-4 py-2"><%= format_currency(order.total_price) %></td>
            <td class="px-4 py-2"><%= format_currency(order.total_original_price) %></td>
            <td class="px-4 py-2"><%= format_currency(order.total_discount) %></td>
            <td class="px-4 py-2"><%= show_invoice_actions(order, "pdf") %></td>
            <td class="px-4 py-2"><%= show_invoice_actions(order, "xml") %></td>
            <td class="px-4 py-2"><%= order.translated_payment_status %></td>
            <td class="px-4 py-2"><%= order.translated_status %></td>
            <% if $global_settings[:feature_flag_sales_attributed_to_seller] %>
              <td class="px-4 py-2">
              <% if order.missing_commission %>
                  <span class="inline-flex items-center px-2 py-1 text-xs font-medium text-red-700 bg-red-50 rounded-md ring-1 ring-inset ring-red-600/10 dark:bg-red-900/20 dark:text-red-400 dark:ring-red-500/20">
                    Sin comisión
                  </span>
                <% end %>
              </td>
            <% end %>
            <td class="px-4 py-2">
              <%= link_to admin_order_path(order), class: "px-4 py-[.4rem] group flex items-center justify-start space-x-3" do %>
                <%= icon "eye", classes: "stroke-current w-5 h-5 text-slate-500 group-hover:text-primary-600 dark:group-hover:text-primary-400" %>
              <% end %>
            </td>
            <% if current_user.any_admin_or_supervisor? %>
              <td class="px-4 py-2">
                <%= link_to edit_admin_order_path(order), class: "px-4 py-[.4rem] group flex items-center justify-start space-x-3" do %>
                  <%= icon "pencil", classes: "stroke-current w-5 h-5 text-slate-500 group-hover:text-primary-600 dark:group-hover:text-primary-400" %>
                <% end %>
              </td>
            <% end %>
            <td class="px-4 py-2">
              <% if current_user.any_admin_or_supervisor? || ($global_settings[:feature_flag_sellers_can_void_orders] && order.created_at > 3.days.ago) %>
                <%= link_to void_admin_order_path(order), data: { turbo_confirm: "¿Estás seguro de que deseas anular esta orden?", turbo_method: :post }, class: "px-4 py-[.4rem] group flex items-center justify-start space-x-3" do %>
                  <%= icon "x-mark", classes: "stroke-current w-5 h-5 text-slate-500 group-hover:text-primary-600 dark:group-hover:text-primary-400" %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/orders/new_orden_de_transporte.html.erb
<%= render "shared/admin/nav", { header_title: "Nueva Orden por Servicio de Transporte" } do %>
  <%= link_to 'Volver a Órdenes de Transporte', orden_de_transporte_index_admin_orders_path, class: 'btn btn-secondary' %>
<% end %>

<div class="px-4 mx-auto mt-8 md:px-10">
  <%= simple_form_for([:admin, @order], url: admin_orders_path) do |form| %>
    <%= render 'shared/form_errors', model: @order %>
    
    <%= form.hidden_field :servicio_transporte, value: true %>
    <%= form.hidden_field :origin, value: "pos" %>
    
    <div class="grid grid-cols-1 gap-6 md:grid-cols-2">
      <!-- Order Date -->
      <div>
        <%= form.label :order_date, "Fecha y Hora", class: "form-label" %>
        <div class="relative">
          <%= form.text_field :order_date,
              value: Time.current.strftime('%Y-%m-%dT%H:%M'),
              class: "form-input w-full",
              type: "datetime-local" %>
        </div>
      </div>

      <!-- Client Selection -->
      <div>
        <label for="user_id" class="form-label">Cliente</label>
        <div class="relative">
          <%= select_tag "user_id",
              options_for_select(@customer_users.map { |u| [u.name, u.customer.id] }),
              { 
                prompt: "Seleccione cliente",
                class: "form-input",
                data: {
                  controller: "select",
                  select_placeholder_value: "Seleccione cliente"
                }
              } %>
        </div>
      </div>

      <!-- Cashier Selection -->
      <div>
        <label for="cashier_id" class="form-label">Caja</label>
        <div class="relative">
          <%= select_tag "cashier_id",
              options_from_collection_for_select(@open_cashiers, :id, :name),
              { 
                prompt: "Seleccione caja",
                class: "form-input",
                data: {
                  controller: "select",
                  select_placeholder_value: "Seleccione caja"
                }
              } %>
        </div>
      </div>

      <!-- Amount Field -->
      <div>
        <label for="amount" class="form-label">Monto en S/</label>
        <div class="relative">
          <%= number_field_tag "amount",
              nil,
              class: "form-input w-full",
              step: "0.01",
              min: "0" %>
        </div>
      </div>
    </div>

    <!-- Wants Factura Checkbox -->
    <div class="mt-6">
      <div class="flex items-center">
        <%= form.check_box :wants_factura, class: "form-checkbox" %>
        <%= form.label :wants_factura, "Requiere Factura", class: "ml-2 form-label" %>
      </div>
    </div>

    <!-- Comments -->
    <div class="mt-6">
      <%= form.label :seller_note, "Comentarios", class: "form-label" %>
      <%= form.text_area :seller_note,
          class: "form-input w-full",
          rows: 3 %>
    </div>

    <div class="flex items-center py-6 mt-10 space-x-4 border-t dark:border-slate-600">
      <%= form.button :submit, "Crear Orden", class: "btn btn-primary" %>
      <%= link_to "Cancelar", 
          orden_de_transporte_index_admin_orders_path, 
          class: "font-medium text-slate-600 hover:text-primary-600 text-sm px-2 py-2 dark:text-slate-400 dark:hover:text-primary-400" %>
    </div>
  <% end %>
</div>

app/views/admin/orders/orden_de_transporte_index.html.erb
<%= render "shared/admin/nav", { header_title: "Órdenes de Servicio de Transporte" } do %>
  <%= link_to "Crear Venta de Servicio de Transporte", new_orden_de_transporte_admin_orders_path, class: "btn btn-primary" %>
<% end %>

<div class="px-4 mb-16" data-controller="datatable" data-datatable-options-value="<%= @datatable_options %>">
  <div class="container p-2 mx-auto mt-6 bg-white rounded-lg border shadow border-slate-300/80 shadow-slate-100 dark:shadow-slate-950 dark:bg-slate-800 dark:border-slate-600/80">
    <table id="datatable-element" class="min-w-full bg-white dark:bg-slate-800">
      <thead>
        <tr>
          <th class="px-4 py-2 text-left">ID</th>
          <% if current_user.any_admin_or_supervisor? %>
            <th class="px-4 py-2 text-left">Tienda</th>
          <% end %>
          <th class="px-4 py-2 text-left">Número</th>
          <th class="px-4 py-2 text-left">Fecha</th>
          <th class="px-4 py-2 text-left">Cliente</th>
          <th class="px-4 py-2 text-left">Total</th>
          <th class="px-4 py-2 text-left">Total Original</th>
          <th class="px-4 py-2 text-left">Descuento</th>
          <th class="px-4 py-2 text-left">Comprobante</th>
          <th class="px-4 py-2 text-left">XML</th>
          <th class="px-4 py-2 text-left">Estado Pago</th>
          <th class="px-4 py-2 text-left">Estado</th>
          <% if $global_settings[:feature_flag_sales_attributed_to_seller] %>
            <th class="px-4 py-2 text-left">Comisión</th>
          <% end %>
          <th class="px-4 py-2 text-left">Ver</th>
          <% if current_user.any_admin_or_supervisor? %>
            <th class="px-4 py-2 text-left">Editar</th>
          <% end %>
          <th class="px-4 py-2 text-left">Anular</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td class="px-4 py-2"><%= order.id %></td>
            <% if current_user.any_admin_or_supervisor? %>
              <td class="px-4 py-2"><%= order.location&.name %></td>
            <% end %>
            <td class="px-4 py-2"><%= order.custom_id %></td>
            <td class="px-4 py-2"><%= friendly_date(current_user, order.order_date) %></td>
            <td class="px-4 py-2"><%= order&.user&.name %></td>
            <td class="px-4 py-2"><%= format_currency(order.total_price) %></td>
            <td class="px-4 py-2"><%= format_currency(order.total_original_price) %></td>
            <td class="px-4 py-2"><%= format_currency(order.total_discount) %></td>
            <td class="px-4 py-2"><%= show_invoice_actions(order, "pdf") %></td>
            <td class="px-4 py-2"><%= show_invoice_actions(order, "xml") %></td>
            <td class="px-4 py-2"><%= order.translated_payment_status %></td>
            <td class="px-4 py-2"><%= order.translated_status %></td>
            <% if $global_settings[:feature_flag_sales_attributed_to_seller] %>
              <td class="px-4 py-2">
                <% if order.missing_commission %>
                  <span class="inline-flex items-center px-2 py-1 text-xs font-medium text-red-700 bg-red-50 rounded-md ring-1 ring-inset ring-red-600/10 dark:bg-red-900/20 dark:text-red-400 dark:ring-red-500/20">
                    Sin comisión
                  </span>
                <% end %>
              </td>
            <% end %>
            <td class="px-4 py-2">
              <%= link_to admin_order_path(order), class: "px-4 py-[.4rem] group flex items-center justify-start space-x-3" do %>
                <%= icon "eye", classes: "stroke-current w-5 h-5 text-slate-500 group-hover:text-primary-600 dark:group-hover:text-primary-400" %>
              <% end %>
            </td>
            <% if current_user.any_admin_or_supervisor? %>
              <td class="px-4 py-2">
                <%= link_to edit_admin_order_path(order), class: "px-4 py-[.4rem] group flex items-center justify-start space-x-3" do %>
                  <%= icon "pencil", classes: "stroke-current w-5 h-5 text-slate-500 group-hover:text-primary-600 dark:group-hover:text-primary-400" %>
                <% end %>
              </td>
            <% end %>
            <td class="px-4 py-2">
              <% if current_user.any_admin_or_supervisor? || ($global_settings[:feature_flag_sellers_can_void_orders] && order.created_at > 7.days.ago) %>
                <%= link_to void_admin_order_path(order), data: { turbo_confirm: "¿Estás seguro de que deseas anular esta orden?", turbo_method: :post }, class: "px-4 py-[.4rem] group flex items-center justify-start space-x-3" do %>
                  <%= icon "x-mark", classes: "stroke-current w-5 h-5 text-slate-500 group-hover:text-primary-600 dark:group-hover:text-primary-400" %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>