config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  mount Shrine.presign_endpoint(:cache) => "/s3/params"

  if Rails.env.development? || Rails.env.test?
    mount Railsui::Engine, at: "/railsui"
  end

  get "pricing", to: "page#pricing"
  get "about", to: "page#about"

  get "invoice/:id", to: "orders#invoice", as: :invoice
  get "invoice_xml/:id", to: "orders#invoice_xml", as: :invoice_xml
  # create a namespace for admin
  namespace :admin do
    resources :products do
      collection do
        get :bulk_tag
        post :apply_bulk_tags
        get :search
        get :search_by_code
        get :search_by_name
        get :search_by_category
        get :search_by_subcategory
        get :search_by_brand
        get :search_by_tag
        get :search_by_barcode
        get :search_by_supplier
        get :search_by_price_range
        get :search_by_stock_range
        get :search_by_created_at
        get :search_by_updated_at
        get :search_by_status
        get :search_by_featured
        get :search_by_discount
        get :search_by_discount_range
        get :search_by_discount_start_date
        get :search_by_discount_end_date
        get :search_by_discount_status
        get :search_by_discount_type
        get :search_by_discount_value
        get :search_by_discount_value_range
        get :search_by_discount_percentage
        get :search_by_discount_percentage_range
        get :search_by_discount_amount
        get :search_by_discount_amount_range
        get :search_by_discount_min_quantity
        get :search_by_discount_max_quantity
        get :search_by_discount_min_amount
        get :search_by_discount_max_amount
        get :search_by_discount_min_percentage
        get :search_by_discount_max_percentage
        get :search_by_discount_min_value
        get :search_by_discount_max_value
        get :search_by_discount_min_created_at
        get :search_by_discount_max_created_at
        get :search_by_discount_min_updated_at
        get :search_by_discount_max_updated_at
        get :search_by_discount_min_start_date
        get :search_by_discount_max_start_date
        get :search_by_discount_min_end_date
        get :search_by_discount_max_end_date
        get :search_by_discount_min_status
        get :search_by_discount_max_status
        get :search_by_discount_min_type
        get :search_by_discount_max_type
        get :search_by_discount_min_value_range
        get :search_by_discount_max_value_range
        get :search_by_discount_min_percentage_range
        get :search_by_discount_max_percentage_range
        get :search_by_discount_min_amount_range
        get :search_by_discount_max_amount_range
        get :customer_prices
        get :default_prices
      end
      resources :media, module: :admin
      post "evaluate_group_discount", on: :collection
      get "search", on: :collection
      get "products_matching_tags", on: :collection
      get "customer_prices", on: :collection
      get "combo_products_show", on: :member
      member do
        get :stock
      end
    end

    resources :products_stock, only: [ :index ]

    post "face_recognition", to: "face_recognition#recognize"

    resources :product_categories, except: [ :show ] do
      resources :media, module: :admin
    end


    resources :requisitions do
      collection do
        get :new_automatic
      end
      member do
        patch :fulfill
      end
      resources :requisition_lines
    end

    resources :orders, only: [ :index, :new, :create, :update, :show, :edit, :update ] do
      member do
        post :retry_invoice
        get :universal_invoice_show
        get :edit_commissions
        get :edit_payments
        patch :update_payments
        post :void
        patch :toggle_wants_factura
      end
      collection do
        get "pos"
        get "orden_de_transporte_index", as: :orden_de_transporte_index
        get "new_orden_de_transporte", as: :new_orden_de_transporte
      end

      resources :external_invoices, only: [ :new, :create, :destroy ]
    end

    resources :voided_orders, only: [ :index, :show ]

    resources :settings, only: [ :index, :edit, :update ]

    resources :payments, only: [ :index, :show, :new, :create ]
    resources :payment_methods
    resources :price_lists
    resources :users do
      member do
        get "loyalty_info"
        patch "update_contact_info"
        get "check_roles"
        get "unpaid_orders"
      end
    end
    get "sellers", to: "users#sellers"

    resources :user_attendance_logs, only: [ :index, :new, :create, :edit, :update ] do
      collection do
        get "check_attendance_status"
        get "seller_checkout"
        get "seller_checkin_status"
        get "location_sellers"
        get "seller_attendance_report"
        get "location_attendance_report"
        post "compare_face"
      end
    end

    resources :customers
    post "pos_create_customer", to: "users#create_customer"
    get "search_dni", to: "customers#search_dni"
    get "search_ruc", to: "customers#search_ruc"

    resources :locations do
      member do
        get :commission_ranges
      end
      collection do
        get :sales_targets
      end
    end
    resources :commission_ranges
    resources :seller_biweekly_sales_targets do
      collection do
        get "seller_data"
      end
    end

    resources :warehouses
    patch "/set_current_warehouse", to: "warehouses#set_current_warehouse"
    get "inventory", to: "inventory/inventory#show"

    namespace :inventory do
      get "kardex", to: "kardex#show"
      get "fetch_kardex_movements", to: "kardex#fetch_kardex_movements"
      get "product_min_max_stocks", to: "product_min_max_stocks#index"
      post "product_min_max_stocks", to: "product_min_max_stocks#create"
      resources :periodic_inventories, only: [ :index, :new, :create, :show ] do
        collection do
          post :print_inventory_list
        end
      end
    end

    resources :stock_transfers do
      collection do
        get "index_stock_adjustments"
      end
      member do
        patch :set_to_in_transit
        get :initiate_receive
        post :execute_receive
        patch :adjustment_stock_transfer_admin_confirm
      end
    end
    post "generate_guia", to: "stock_transfers#generate_guia"
    resources :planned_stock_transfers do
      member do
        post :create_stock_transfer
      end
    end
    resources :in_transit_stocks
    resources :transportistas
    resources :combo_products
    resources :product_packs
    resources :discount_products
    resources :discounts do
      get "matching_products", on: :collection
    end
    resources :cashier_shifts do
      member do
        patch :close
        patch :modify_initial_balance
      end
    end

    resources :cashier_transactions, only: [ :new, :create ]
    resources :commissions, only: [ :index, :show ]
    resources :loyalty_tiers
    resources :invoicers do
      get "invoice_series", on: :member
    end
    resources :invoice_series
    resources :invoice_series_mappings

    resources :tags, only: [ :index, :new, :create, :edit, :update, :destroy ]

    resources :account_receivables, only: [ :index, :show ] do
      get "users_index", on: :collection
      get "payments_calendar", on: :collection
      post "create_initial_balance", on: :collection
    end

    resources :account_receivable_payments do
      collection do
        get :success
        get :error
      end
    end

    resources :purchase_orders do
      member do
        post :create_purchase
      end
      collection do
        get :get_product_details
      end
    end

    resources :purchases do
      collection do
        get :get_purchase_order_details
        get :get_product_details
        get :check_invoice_custom_id
      end
    end

    resources :purchase_invoices

    resources :vendors

    resources :purchase_payments, only: [ :index, :show, :new, :create ] do
      collection do
        get :fetch_purchases
      end
    end

    resources :account_payables, only: [ :index, :show ] do
      collection do
        get :vendors_index
        get :payments_calendar
        post :create_initial_balance
      end
    end

    resources :account_payable_payments do
      collection do
        get :success
        get :error
      end
    end

    resources :orders_per_product, only: [ :index ] do
      collection do
        get :reset_filters
      end
    end

    get "sales_dashboard", to: "dashboards#sales_dashboard"
    get "cashiers_dashboard", to: "dashboards#cashiers_dashboard"
    get "sales_ranking", to: "dashboards#sales_ranking"
    post "dashboards/set_location", to: "dashboards#set_location"

    resources :dashboards, only: [] do
      collection do
        get :payments_calendar
      end
    end

    get "reports/form", to: "reports#reports_form"
    post "reports/generate", to: "reports#generate"
    get "reports/cash_flow", to: "reports#cash_flow"
    get "reports/inventory_out", to: "reports#inventory_out"
    get "reports/consolidated", to: "reports#consolidated"

    resources :consolidated_sales, only: [ :index ]
    get "reports/consolidated_sales", to: "consolidated_sales#index"

    resources :sales_per_seller, only: [ :index ] do
      collection do
        get :consolidated
      end
    end
    get "reports/sales_per_seller", to: "sales_per_seller#index"
    get "reports/sales_per_seller/consolidated", to: "sales_per_seller#consolidated"

    resources :flat_commission_products_report, only: [ :index ]
    get "reports/flat_commission_products_report", to: "flat_commission_products_report#index"

    resources :grouped_sales, only: [ :index ]
    get "reports/grouped_sales", to: "grouped_sales#index"

    resources :stock_transfers_with_differences, only: [ :index ] do
      member do
        put :accept_origin_quantity
        put :accept_destination_quantity
      end

app/models/user_attendance_log.rb
class UserAttendanceLog < ApplicationRecord
  include TranslateEnum
  audited_if_enabled
  belongs_to :user
  belongs_to :location

  attr_accessor :captured_photo

  validates :checkin, presence: true
  validate :user_not_checked_in_elsewhere, on: :create

  scope :current, -> { where(checkout: nil) }

  enum :status, [ :active, :inactive ]
  translate_enum :status

  after_commit :update_user_location, if: :should_update_user_location?

  def update_user_location
    latest_log = user.user_attendance_logs.order(checkin: :desc).first

    if self == latest_log
      if self.checkout.present?
        user.update(location_id: nil)
      else
        user.update(location_id: self.location_id)
      end
    end
  end

  def self.checkin(user, location)
    create!(user: user, location: location, checkin: Time.current)
    user.update(last_checkin_at: Time.current, location_id: location.id)
  end

  def self.checkout(user, location)
    current.find_by(user: user, location: location).update(checkout: Time.current)
  end

  private

    def should_update_user_location?
      saved_change_to_checkin? || saved_change_to_checkout?
    end

    def user_not_checked_in_elsewhere
      if user.user_attendance_logs.current.exists?
        errors.add(:base, "El vendedor ya tiene un checkin en otra tienda")
      end
    end
end

app/views/admin/user_attendance_logs/_actions.html.erb
<div data-controller="dropdown" class="relative">
  <button data-action="click->dropdown#toggle click@window->dropdown#hide"
          class="p-2 rounded-lg focus:ring-4 focus:ring-primary-50 dark:focus:ring-slate-600/50">
    <%= icon "cog-6-tooth", classes: "w-6 h-6 stroke-current text-slate-500 group-hover:text-primary-600 dark:group-hover:text-primary-400" %>
  </button>
  <ul data-dropdown-target="menu"
      class="hidden absolute right-0 top-10 bg-white rounded-lg shadow-xl dark:bg-slate-700 dark:shadow-slate-900/50 dark:border-slate-500/60 w-[200px] z-50 py-2">
    <% default_object_options_array.each do |option| %>
      <li>
        <%= link_to "#", data: { action: "click->dropdown#handleAction", test_id: "test", object_id: user_attendance_log.id, event_name: option[:event_name], edit_url: edit_admin_user_attendance_log_path(user_attendance_log), destroy_url: admin_user_attendance_log_path(user_attendance_log) }, class: "px-4 py-[.4rem] group flex items-center justify-start space-x-3" do %>
          <%= icon option[:icon], classes: "stroke-current w-5 h-5 text-slate-500 group-hover:text-primary-600 dark:group-hover:text-primary-400" %>
          <span><%= option[:label] %></span>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/admin/user_attendance_logs/_form.html.erb
<div class="container p-6 mx-auto mt-6">
  <div class="w-full">
    <div class="p-6 mb-6 bg-white border rounded-lg shadow border-slate-300/80 shadow-slate-100 dark:shadow-slate-950 dark:bg-slate-800 dark:border-slate-600/80">
      <%= simple_form_for([:admin, user_attendance_log], html: { class: "space-y-4", data: { controller: "attendance-form webcam", webcam_admin_or_supervisor_value: @user_is_admin_or_supervisor, attendance_form_admin_or_supervisor_value: @user_is_admin_or_supervisor } }) do |f| %>
        <%= render 'shared/form_errors', model: user_attendance_log %>

        <div>
          <%= f.association :location,
              collection: @elligible_locations,
              label: "Ubicación", 
              input_html: { 
                class: "mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md",
                data: { action: "change->attendance-form#checkAttendanceStatus" },
                disabled: user_attendance_log.persisted?
              },
              include_blank: false,
              selected: (@elligible_locations.one? ? @elligible_locations.first.id : nil),
              label_html: { 
                class: "block text-sm font-medium text-gray-700 dark:text-gray-300" 
              } %>
          <% if user_attendance_log.persisted? %>
            <%= f.hidden_field :location_id %>
          <% end %>
        </div>

        <div>
          <%= f.association :user, 
              collection: @elligible_sellers, 
              label: "Vendedor", 
              input_html: { 
                class: "mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md",
                data: { 
                  webcam_target: "userIdInput",
                  controller: "select",
                  select_model_value: "User",
                  select_multi_select_value: false,
                  select_placeholder_value: "Seleccione un vendedor",
                  action: "change->attendance-form#checkAttendanceStatus"
                },
                disabled: user_attendance_log.persisted?
              }, 
              label_html: { 
                class: "block text-sm font-medium text-gray-700 dark:text-gray-300" 
              } %>
          <% if user_attendance_log.persisted? %>
            <%= f.hidden_field :user_id %>
          <% end %>
        </div>

        <div>
          <%= f.input :checkin, 
              as: :datetime, 
              label: "Hora de Checkin", 
              input_html: { 
                class: "mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md",
                data: { attendance_form_target: "checkinField" },
                value: @current_time
              }, 
              label_html: { 
                class: "block text-sm font-medium text-gray-700 dark:text-gray-300" 
              },
              html5: true %>
        </div>

        <div data-attendance-form-target="checkoutField" class="hidden">
          <%= f.input :checkout, 
              as: :datetime, 
              label: "Hora de Checkout", 
              input_html: { 
                class: "mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md"
              }, 
              label_html: { 
                class: "block text-sm font-medium text-gray-700 dark:text-gray-300" 
              },
              html5: true %>
        </div>

        <div>
          <video data-webcam-target="video" width="640" height="480" autoplay playsinline></video>
          <canvas data-webcam-target="canvas" width="640" height="480" style="display: none;"></canvas>
          <button type="button" data-action="webcam#capture" data-webcam-target="captureButton" class="mt-4 btn btn-secondary">Capturar Foto</button>
          <%= f.input :captured_photo, as: :hidden, input_html: { data: { webcam_target: "photoInput" } } %>
          <div data-webcam-target="message" class="mt-2 text-sm text-gray-600"></div>
        </div>

        <%= f.button :submit, 'Grabar', 
          class: "btn btn-primary", 
          data: { 
            webcam_target: "submitButton", 
            action: "click->attendance-form#submitForm"
          } %>
      <% end %>
    </div>

    <!-- Already Checked-in Users Table -->
    <div class="p-6 bg-white border rounded-lg shadow border-slate-300/80 shadow-slate-100 dark:shadow-slate-950 dark:bg-slate-800 dark:border-slate-600/80">
      <h4 class="mb-4 text-lg font-medium text-gray-900 dark:text-gray-100">Vendedores con checkin registrados:</h4>
      <% if @already_checked_in_users.any? %>
        <div class="overflow-x-auto">
          <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
              <tr>
                <th scope="col" class="px-6 py-3">Vendedor</th>
                <th scope="col" class="px-6 py-3">Ubicación</th>
                <th scope="col" class="px-6 py-3">Hora de Check-in</th>
                <th scope="col" class="px-6 py-3">Acción</th>
              </tr>
            </thead>
            <tbody>
              <% @already_checked_in_users.each do |user| %>
                <% attendance_log = user.user_attendance_logs.find_by(checkout: nil) %>
                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                  <td class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    <%= user.name %>
                  </td>
                  <td class="px-6 py-4">
                    <%= attendance_log&.location&.name || 'No especificada' %>
                  </td>
                  <td class="px-6 py-4">
                    <%= attendance_log&.checkin&.strftime("%d/%m/%Y %H:%M") || '' %>
                  </td>
                  <td class="px-6 py-4">
                    <%= link_to seller_checkout_admin_user_attendance_logs_path(user_id: user.id, location_id: attendance_log.location_id), class: "text-blue-600 hover:text-blue-900 dark:text-blue-400 dark:hover:text-blue-600" do %>
                      <i class="fas fa-sign-out-alt"></i> <!-- Assuming you're using Font Awesome for icons -->
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% else %>
        <p class="text-sm text-gray-700 dark:text-gray-300">No hay vendedores registrados actualmente.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/user_attendance_logs/edit.html.erb
<%= render "shared/admin/nav", { header_title: "Editar Check-in de Vendedor" } do %>
<% end %>

<div class="container px-4 py-8 mx-auto sm:px-6 lg:px-8" data-attendance-form-edit="true">
  <div class="max-w-3xl mx-auto">
    <div class="overflow-hidden bg-white shadow sm:rounded-lg">
      <div class="px-4 py-5 sm:px-6">
        <h3 class="text-lg font-medium leading-6 text-gray-900">
          Editar Checkin de Vendedor
        </h3>
        <p class="max-w-2xl mt-1 text-sm text-gray-500">
          Modifica los detalles del checkin de un vendedor.
        </p>
      </div>
      <div class="px-4 py-5 border-t border-gray-200 sm:p-0">
        <div class="sm:px-6 sm:py-5">
          <%= render 'form', user_attendance_log: @user_attendance_log %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/user_attendance_logs/index.html.erb
<%= render "shared/admin/nav", { header_title: "Registros de Asistencia" } do %>
<% end %>

<div class="px-4 mb-16" data-controller="datatable attendance-logs" data-datatable-options-value="<%= @datatable_options %>">
  <div class="container p-2 mx-auto mt-6 bg-white border rounded-lg shadow border-slate-300/80 shadow-slate-100 dark:shadow-slate-950 dark:bg-slate-800 dark:border-slate-600/80">
    <div class="flex items-center justify-between mb-4">
      <div class="flex items-center gap-4">
        <% if current_user.any_admin_or_supervisor? %>
          <%= form_tag admin_user_attendance_logs_path, method: :get, class: "flex items-center gap-4", 
              data: { action: "submit->attendance-logs#refreshTable" } do %>
            <%= select_tag :location_id, 
                         options_from_collection_for_select(@locations, :id, :name, @filter_location_id), 
                         prompt: "Todas las ubicaciones",
                         class: "form-select w-[220px] max-w-[220px]",
                         data: { action: "change->attendance-logs#refreshTable" } %>
            
            <div class="flex items-center gap-2">
              <%= datetime_field_tag :begin_datetime, 
                                   @filter_begin_datetime, 
                                   class: "form-input",
                                   placeholder: "Fecha inicial" %>
              <%= datetime_field_tag :end_datetime, 
                                   @filter_end_datetime, 
                                   class: "form-input",
                                   placeholder: "Fecha final" %>
            </div>
            
            <%= submit_tag "Filtrar", class: "btn btn-primary" %>
            
            <% if params[:location_id].present? || params[:begin_datetime].present? || params[:end_datetime].present? || session[:user_attendance_filter_location_id].present? || session[:user_attendance_filter_begin_datetime].present? || session[:user_attendance_filter_end_datetime].present? %>
              <%= link_to admin_user_attendance_logs_path(clear_filters: true), 
                class: "btn btn-secondary w-[300px] max-w-[160px]", 
                  data: { action: "attendance-logs#removeFilters" } do %>
                <i class="mr-1 fas fa-times"></i> Quitar Filtros
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

    <table id="datatable-element" class="min-w-full bg-white dark:bg-slate-800">
      <thead>
        <tr>
          <th class="px-4 py-2 text-left">Vendedor</th>
          <th class="px-4 py-2 text-left">Ubicación</th>
          <th class="px-4 py-2 text-left">Hora de Check-in</th>
          <th class="px-4 py-2 text-left">Hora de Check-out</th>
          <th class="px-4 py-2 text-left">Estado</th>
          <th class="px-4 py-2 text-left">Acciones</th>
        </tr>
      </thead>
      <tbody>
        <!-- Table body will be populated by DataTables -->
      </tbody>
    </table>
  </div>
</div>

app/views/admin/user_attendance_logs/new.html.erb
<%= render "shared/admin/nav", { header_title: "Nuevo Checkin / Checkout de Vendedor" } do %>
<% end %>

<div class="container px-4 py-8 mx-auto sm:px-6 lg:px-8">
  <div class="max-w-3xl mx-auto">
    <div class="overflow-hidden bg-white shadow sm:rounded-lg">
      <div class="px-4 py-5 sm:px-6">
        <h3 class="text-lg font-medium leading-6 text-gray-900">
          Nuevo Checkin / Checkout de Vendedor
        </h3>
        <p class="max-w-2xl mt-1 text-sm text-gray-500">
          Registra un nuevo checkin o checkout para un vendedor.
        </p>
      </div>
      <div class="px-4 py-5 border-t border-gray-200 sm:p-0">
        <div class="sm:px-6 sm:py-5">
          <%= render 'form', user_attendance_log: @user_attendance_log %>
        </div>
      </div>
    </div>
  </div>
</div>